source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'WangyuxiangLivevideo' do
    pod 'Alamofire'
    pod 'Kingfisher','~>2.6'
    pod 'MJRefresh'
    pod 'SnapKit','~>0.22.0'
    pod 'SwiftyJSON'
    pod 'XWSwiftRefresh', '~> 0.1.9'
    pod 'AMap3DMap'
    pod 'AMapSearch'
    pod 'AMapLocation'
    pod 'HyphenateLite_CN'
    pod 'ShareSDK3'
    pod 'MOBFoundation'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'ShareSDK3/ShareSDKExtension'

end
